[versions]
shadow = "8.1.1"
spotless = "6.25.0"

# Version declaration for GSON.
gson = "2.10.1"

[libraries]
gson = { group = "com.google.code", name = "gson", version.ref = "gson" }

[plugins]
shadow = { id = "io.github.goooler.shadow", version.ref = "shadow" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
